# To add a new cell, type '# %%'
# To add a new markdown cell, type '# %% [markdown]'
# %%

import csv
processes_raw = '''
products_jackets products_trousers products_knitted
products_shirts
products_shirts products_ladiesshirts products_dresses products_children products_outerwear products_nightwear
products_shirts products_jackets products_trousers
products_ladiesshirts products_knitted
products_jackets products_children products_outerwear
products_trousers
products_sweaters
products_shirts products_children products_outerwear
products_shirts products_dresses products_children products_trousers products_knitted
products_jackets products_outerwear
products_shirts products_children products_outerwear products_vest
products_ladiesshirts products_children products_outerwear products_knitted products_vest
products_shirts products_ladiesshirts products_children products_trousers
products_ladiesshirts products_children products_knitted products_other
products_other
products_vest products_other
products_children products_outerwear products_knitted products_other
products_shirts products_ladiesshirts products_outerwear
products_outerwear
products_knitted
products_shirts products_ladiesshirts products_other
products_jackets products_outerwear products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_coordinate products_vest
products_jackets products_children products_outerwear products_trousers products_sportswear products_vest products_other
products_ladiesshirts products_jackets products_coats products_outerwear products_nightwear
products_shirts products_ladiesshirts products_jackets products_coats products_trousers products_knitted products_sportswear
products_outerwear products_trousers products_other
products_trousers products_other
products_outerwear products_other
products_undergarments
products_shirts products_ladiesshirts
products_ladiesshirts products_jackets products_children products_outerwear products_sportswear products_nightwear products_other
products_jackets products_children products_knitted products_sportswear products_other
products_children products_trousers products_knitted
products_children products_trousers products_knitted products_nightwear products_undergarments
products_ladiesshirts products_jackets products_coats products_outerwear products_sportswear products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_children products_knitted products_sportswear products_nightwear products_vest products_other
products_ladiesshirts products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_sportswear products_nightwear products_coordinate
products_shirts products_ladiesshirts products_coats products_dresses products_children products_outerwear products_trousers products_nightwear products_other
products_jackets products_children products_sweaters
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments
products_children products_knitted
products_shirts products_ladiesshirts products_children products_outerwear
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted products_nightwear
products_shirts products_ladiesshirts products_trousers products_knitted products_other
products_shirts products_jackets products_dresses products_children products_outerwear products_trousers products_sportswear products_vest
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_nightwear products_coordinate
products_ladiesshirts products_jackets products_children products_outerwear products_trousers
products_shirts products_ladiesshirts products_jackets products_coats products_children products_outerwear products_trousers
products_shirts products_children
products_ladiesshirts products_children products_outerwear products_trousers products_knitted products_nightwear
products_children products_knitted products_sportswear products_other
products_children products_outerwear products_knitted products_sportswear products_nightwear products_undergarments
products_children products_outerwear
products_jackets products_children products_outerwear products_trousers
products_shirts products_ladiesshirts products_children
products_shirts products_ladiesshirts products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_other
products_jackets products_children products_outerwear products_trousers products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_children products_outerwear products_other
products_trousers products_knitted products_sportswear products_undergarments
products_outerwear products_trousers products_knitted products_sportswear
products_knitted products_nightwear products_undergarments
products_trousers products_knitted products_vest
products_coats products_other
products_shirts products_sweaters
products_ladiesshirts products_jackets products_coats products_children products_outerwear products_trousers products_sportswear products_nightwear products_vest
products_ladiesshirts products_jackets products_children products_trousers products_sweaters
products_jackets products_knitted
products_ladiesshirts products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers
products_children products_sweaters products_vest products_other
products_ladiesshirts products_trousers products_other
products_sweaters products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_trousers
products_knitted products_sportswear products_other
products_ladiesshirts products_outerwear products_trousers
products_jackets products_trousers products_sportswear
products_knitted products_undergarments products_other
products_jackets products_other
products_ladiesshirts products_jackets products_trousers products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_dresses products_children
products_trousers products_knitted
products_outerwear products_knitted products_undergarments products_other
products_shirts products_trousers
products_trousers products_undergarments
products_jackets products_outerwear products_trousers
products_children products_trousers products_knitted products_sportswear products_nightwear products_other
products_knitted products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_knitted products_other
products_jackets products_outerwear products_sportswear products_vest products_other
products_ladiesshirts products_jackets products_sportswear products_vest
products_shirts products_ladiesshirts products_knitted
products_shirts products_ladiesshirts products_jackets products_dresses products_outerwear products_trousers products_other
products_jackets products_outerwear products_other
products_knitted products_sportswear products_nightwear products_undergarments products_vest
products_children products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_outerwear products_trousers
products_jackets products_children products_outerwear products_undergarments
products_shirts products_ladiesshirts products_jackets products_children products_outerwear
products_shirts products_ladiesshirts products_children products_outerwear products_sweaters
products_shirts products_children products_outerwear products_trousers products_knitted
products_children products_trousers
products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_sportswear products_vest
products_children products_knitted products_nightwear
products_ladiesshirts
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_nightwear
products_trousers products_knitted products_nightwear
products_jackets products_knitted products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_knitted products_nightwear
products_shirts products_ladiesshirts products_jackets products_children products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_knitted products_sportswear
products_jackets products_coats products_outerwear products_trousers products_sportswear products_vest
products_shirts products_knitted
products_shirts products_ladiesshirts products_dresses products_children products_nightwear products_other
products_jackets products_coats products_other
products_shirts products_ladiesshirts products_jackets products_trousers products_other
products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_sportswear products_vest
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_knitted products_sportswear products_nightwear
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_children products_sportswear products_nightwear products_vest products_other
products_ladiesshirts products_children products_knitted products_sportswear products_nightwear products_undergarments products_vest
products_ladiesshirts products_children products_knitted products_sportswear products_nightwear products_undergarments products_vest products_other
products_knitted products_sportswear products_undergarments
products_shirts products_ladiesshirts products_children products_knitted
products_shirts products_ladiesshirts products_jackets products_coats products_children products_outerwear
products_ladiesshirts products_jackets products_children products_outerwear
products_ladiesshirts products_jackets
products_ladiesshirts products_children products_outerwear products_other
products_shirts products_ladiesshirts products_outerwear products_other
products_ladiesshirts products_jackets products_outerwear products_trousers products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_nightwear
products_jackets products_children
products_shirts products_ladiesshirts products_dresses products_children products_outerwear products_trousers
products_children products_outerwear products_knitted products_nightwear products_other
products_knitted products_sportswear products_nightwear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_knitted
products_ladiesshirts products_children products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_knitted products_sportswear products_nightwear products_undergarments
products_ladiesshirts products_knitted products_sportswear products_nightwear products_vest
products_shirts products_children products_trousers
products_jackets products_coats products_dresses products_children products_outerwear products_trousers
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_sportswear
products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments
products_shirts products_ladiesshirts products_jackets products_trousers
products_ladiesshirts products_outerwear products_trousers products_other
products_ladiesshirts products_children
products_knitted products_sportswear
products_knitted products_nightwear products_other
products_shirts products_jackets products_coats products_dresses products_children products_trousers products_sportswear
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted products_sportswear products_nightwear products_vest
products_shirts products_jackets products_outerwear products_trousers products_other
products_jackets products_outerwear products_knitted products_sportswear products_other
products_trousers products_sportswear products_vest
products_children
products_ladiesshirts products_trousers products_knitted products_other
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted products_vest products_other
products_jackets products_trousers products_knitted products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_coats products_children products_outerwear products_trousers products_other
products_ladiesshirts products_children products_outerwear products_trousers products_other
products_jackets products_children products_outerwear products_trousers products_knitted products_sportswear
products_ladiesshirts products_jackets products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets
products_shirts products_ladiesshirts products_trousers
products_ladiesshirts products_children products_outerwear products_trousers products_sportswear products_other
products_children products_trousers products_other
products_ladiesshirts products_outerwear products_knitted products_sportswear products_nightwear
products_children products_outerwear products_knitted products_sportswear products_nightwear
products_children products_sweaters
products_ladiesshirts products_jackets products_children products_knitted products_nightwear products_other
products_shirts products_ladiesshirts products_children products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_vest
products_children products_outerwear products_trousers
products_children products_trousers products_knitted products_other
products_shirts products_knitted products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_sportswear
products_gloves products_other
products_ladiesshirts products_children products_outerwear products_knitted products_nightwear products_other
products_ladiesshirts products_jackets products_coats products_dresses products_outerwear products_knitted products_nightwear products_undergarments products_other
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_trousers products_nightwear products_other
products_ladiesshirts products_jackets products_children products_knitted products_other
products_children products_trousers products_knitted products_vest products_other
products_shirts products_ladiesshirts products_children products_other
products_jackets products_coats products_children products_trousers products_sportswear products_other
products_shirts products_outerwear products_trousers
products_children products_outerwear products_knitted products_sportswear
products_outerwear products_trousers
products_children products_knitted products_other
products_dresses products_trousers products_knitted products_sportswear
products_children products_other
products_jackets products_children products_trousers products_other
products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted
products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_sportswear products_vest
products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_dresses products_other
products_shirts products_ladiesshirts products_jackets products_other
products_shirts products_coats products_trousers
products_sportswear
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted
products_children products_trousers products_sportswear products_other
products_shirts products_ladiesshirts products_dresses products_children products_trousers products_sportswear products_nightwear
products_ladiesshirts products_jackets products_trousers products_sportswear
products_coats products_dresses products_children products_trousers
products_children products_trousers products_sweaters products_other
products_ladiesshirts products_jackets products_trousers products_sportswear products_other
products_shirts products_children products_trousers products_other
products_shirts products_ladiesshirts products_trousers products_other
products_outerwear products_trousers products_sportswear
products_jackets products_outerwear products_trousers products_sportswear
products_shirts products_ladiesshirts products_dresses products_children products_outerwear products_nightwear products_other
products_shirts products_ladiesshirts products_children products_trousers products_knitted
products_shirts products_ladiesshirts products_knitted products_sportswear
products_children products_outerwear products_trousers products_knitted products_other
products_jackets products_children products_knitted products_sportswear
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_other
products_ladiesshirts products_children products_other
products_shirts products_ladiesshirts products_jackets products_outerwear products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_trousers products_knitted products_sportswear products_nightwear
products_shirts products_children products_outerwear products_knitted products_sportswear products_nightwear products_vest products_other
products_shirts products_jackets products_children products_outerwear products_trousers
products_trousers products_sportswear products_other
products_children products_knitted products_nightwear products_other
products_ladiesshirts products_jackets products_children products_trousers products_knitted
products_shirts products_ladiesshirts products_children products_knitted products_nightwear products_other
products_shirts products_ladiesshirts products_coats products_children products_outerwear products_sportswear
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_sportswear products_nightwear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers
products_jackets products_children products_trousers products_knitted
products_jackets products_knitted products_sweaters
products_jackets products_dresses products_children products_outerwear products_trousers products_vest
products_shirts products_ladiesshirts products_jackets products_coats products_trousers products_knitted products_vest products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_sportswear products_vest
products_shirts products_jackets products_other
products_jackets products_trousers products_other
products_shirts products_ladiesshirts products_children products_outerwear products_knitted products_other
products_shirts products_jackets products_children products_trousers
products_shirts products_jackets products_children products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_children products_trousers
products_shirts products_ladiesshirts products_dresses products_children products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_coats products_trousers products_other
products_ladiesshirts products_jackets products_children products_knitted
products_shirts products_ladiesshirts products_dresses products_children products_sportswear
products_jackets products_trousers
products_jackets products_outerwear products_trousers products_other
products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_vest
products_trousers products_knitted products_sportswear
products_shirts products_ladiesshirts products_children products_outerwear products_trousers
products_jackets products_outerwear products_sweaters
products_ladiesshirts products_jackets products_children products_trousers
products_jackets products_children products_trousers products_knitted products_sportswear products_other
products_trousers products_knitted products_sportswear products_undergarments products_other
products_jackets products_dresses products_children products_outerwear products_trousers products_sportswear products_vest
products_children products_outerwear products_other
products_shirts products_trousers products_other
products_ladiesshirts products_jackets products_children products_trousers products_other
products_jackets products_knitted products_undergarments
products_children products_outerwear products_knitted products_sportswear products_nightwear products_other
products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_other
products_sweaters products_vest products_other
products_shirts products_ladiesshirts products_jackets products_children
products_jackets products_knitted products_sportswear products_other
products_shirts products_children products_outerwear products_other
products_ladiesshirts products_jackets products_children products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_other
products_shirts products_children products_outerwear products_trousers
products_jackets products_coats products_sweaters
products_ladiesshirts products_children products_trousers products_other
products_children products_trousers products_knitted products_nightwear
products_children products_sweaters products_other
products_jackets products_outerwear products_trousers products_knitted products_other
products_sweaters products_vest
products_ladiesshirts products_trousers products_knitted products_sportswear products_undergarments
products_shirts products_dresses products_children products_trousers
products_children products_trousers products_knitted products_sportswear products_nightwear products_vest
products_ladiesshirts products_jackets products_trousers products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_other
products_shirts products_dresses products_trousers products_knitted products_sweaters
products_jackets products_children products_trousers
products_ladiesshirts products_coats products_children products_trousers products_other
products_shirts products_ladiesshirts products_children products_outerwear products_trousers products_knitted products_sportswear
products_shirts products_ladiesshirts products_jackets products_outerwear products_knitted products_nightwear
products_shirts products_jackets products_knitted products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_knitted products_nightwear products_vest
products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_nightwear products_vest
products_shirts products_jackets products_knitted products_other
products_shirts products_ladiesshirts products_dresses products_children products_other
products_jackets products_children products_outerwear products_trousers products_other
products_children products_knitted products_undergarments products_other
products_shirts products_ladiesshirts products_dresses products_children products_trousers
products_shirts products_ladiesshirts products_children products_knitted products_sportswear products_nightwear
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_knitted
products_ladiesshirts products_children products_trousers products_knitted products_undergarments products_vest
products_children products_trousers products_knitted products_undergarments
products_jackets products_dresses products_children products_trousers
products_ladiesshirts products_jackets products_children products_trousers products_knitted products_nightwear
products_children products_trousers products_knitted products_sportswear products_nightwear products_vest products_other
products_shirts products_other
products_jackets products_dresses products_children products_outerwear products_trousers
products_shirts products_ladiesshirts products_children products_knitted products_nightwear products_coordinate
products_jackets products_children products_knitted
products_jackets products_sweaters
products_shirts products_jackets products_coats products_children products_trousers products_sportswear products_other
products_children products_knitted products_sportswear products_nightwear
products_dresses
products_children products_outerwear products_trousers products_other
products_jackets products_children products_trousers products_sportswear products_nightwear
products_shirts products_ladiesshirts products_children products_trousers products_sportswear products_nightwear
products_shirts products_ladiesshirts products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_dresses products_outerwear products_trousers products_knitted
products_shirts products_children products_knitted products_undergarments products_other
products_shirts products_children products_other
products_jackets products_children products_trousers products_knitted products_sportswear products_nightwear products_vest
products_shirts products_ladiesshirts products_dresses
products_ladiesshirts products_outerwear
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_knitted products_nightwear products_sweaters
products_jackets products_children products_outerwear products_sportswear products_vest products_other
products_shirts products_ladiesshirts products_children products_outerwear products_knitted
products_jackets
products_ladiesshirts products_jackets products_trousers products_knitted products_nightwear
products_jackets products_coats products_children products_trousers products_knitted products_nightwear
products_children products_knitted products_undergarments
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear
products_jackets products_trousers products_knitted products_other
products_shirts products_ladiesshirts products_jackets products_coats products_trousers products_nightwear products_other
products_shirts products_ladiesshirts products_children products_outerwear products_trousers products_sportswear products_other
products_jackets products_dresses products_children products_trousers products_sportswear products_vest products_other
products_jackets products_knitted products_sportswear
products_jackets products_children products_trousers products_knitted products_nightwear
products_jackets products_children products_trousers products_knitted products_other
products_ladiesshirts products_coats products_children products_outerwear
products_shirts products_ladiesshirts products_jackets products_coats products_children products_knitted products_sportswear
products_shirts products_ladiesshirts products_children products_trousers products_knitted products_sportswear
products_vest
products_shirts products_ladiesshirts products_jackets products_coats products_children products_outerwear products_knitted products_sweaters
products_shirts products_nightwear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_sweaters products_other
products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_other
products_trousers products_knitted products_nightwear products_undergarments
products_shirts products_jackets products_children products_knitted
products_undergarments products_other
products_outerwear products_knitted
products_ladiesshirts products_children products_undergarments
products_jackets products_children products_trousers products_knitted products_undergarments products_other
products_jackets products_dresses products_children products_outerwear products_trousers products_sportswear
products_shirts products_jackets products_trousers products_other
products_gloves products_sweaters products_vest products_other
products_shirts products_trousers products_knitted
products_children products_trousers products_knitted products_sweaters
products_trousers products_knitted products_other
products_jackets products_children products_trousers products_nightwear
products_knitted products_sportswear products_nightwear products_undergarments
products_shirts products_ladiesshirts products_dresses products_children products_knitted
products_dresses products_children products_trousers products_knitted products_undergarments
products_shirts products_ladiesshirts products_knitted products_other
products_ladiesshirts products_children products_trousers
products_shirts products_jackets products_children products_knitted products_sportswear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_sweaters
products_shirts products_ladiesshirts products_trousers products_knitted products_sportswear products_nightwear products_sweaters products_other
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted products_sportswear products_undergarments products_vest
products_shirts products_jackets products_children products_trousers products_other
products_shirts products_ladiesshirts products_dresses products_children products_outerwear products_knitted
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_sweaters products_vest
products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_sportswear products_vest products_other
products_knitted products_sportswear products_vest products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_sweaters
products_shirts products_ladiesshirts products_jackets products_coats products_trousers products_sportswear products_vest products_other
products_shirts products_ladiesshirts products_jackets products_dresses products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_vest products_other
products_ladiesshirts products_jackets products_trousers products_knitted products_other
products_children products_outerwear products_trousers products_knitted
products_children products_trousers products_vest products_other
products_ladiesshirts products_children products_knitted products_sportswear products_nightwear products_undergarments products_other
products_dresses products_children products_outerwear products_trousers products_knitted
products_ladiesshirts products_jackets products_children products_trousers products_knitted products_nightwear products_undergarments
products_knitted products_sportswear products_nightwear products_undergarments products_other
products_children products_outerwear products_knitted
products_ladiesshirts products_jackets products_dresses products_children products_outerwear products_trousers
products_jackets products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_knitted products_sportswear
products_shirts products_ladiesshirts products_jackets products_dresses products_children products_trousers products_knitted products_sportswear products_sweaters
products_shirts products_ladiesshirts products_children products_trousers products_sportswear
products_shirts products_ladiesshirts products_jackets products_coats products_children products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_vest
products_dresses products_children products_trousers products_knitted products_sportswear
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_knitted products_nightwear products_undergarments
products_shirts products_ladiesshirts products_children products_trousers products_knitted products_sportswear products_undergarments
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted products_sweaters
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_sweaters
products_trousers products_sportswear
products_ladiesshirts products_children products_trousers products_knitted products_other
products_children products_knitted products_sportswear
products_ladiesshirts products_outerwear products_knitted
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted products_other
products_ladiesshirts products_children products_outerwear products_knitted
products_shirts products_ladiesshirts products_jackets products_coats products_outerwear products_knitted
products_knitted products_undergarments
products_jackets products_dresses products_trousers products_knitted products_nightwear products_undergarments products_other
products_outerwear products_trousers products_sweaters
products_children products_outerwear products_trousers products_knitted products_sportswear products_undergarments products_other
products_shirts products_ladiesshirts products_dresses products_children products_trousers products_other
products_shirts products_ladiesshirts products_jackets products_children products_knitted
products_jackets products_children products_trousers products_knitted products_sportswear products_nightwear products_undergarments products_other
products_shirts products_ladiesshirts products_jackets products_coats products_dresses products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_knitted products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted products_sweaters products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_undergarments
products_shirts products_ladiesshirts products_jackets products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_outerwear products_trousers products_knitted products_sweaters products_other
products_shirts products_ladiesshirts products_outerwear products_trousers products_sportswear products_other
products_shirts products_ladiesshirts products_jackets products_coats products_children products_knitted products_other
products_children products_knitted products_nightwear products_undergarments
products_children products_trousers products_knitted products_undergarments products_other
products_ladiesshirts products_jackets products_children products_trousers products_nightwear products_other
products_shirts products_trousers products_knitted products_sportswear
products_shirts products_outerwear products_trousers products_knitted products_sportswear products_other
products_jackets products_children products_knitted products_other
products_shirts products_ladiesshirts products_outerwear products_trousers products_other
products_shirts products_ladiesshirts products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_children products_outerwear products_trousers products_other
products_shirts products_ladiesshirts products_children products_outerwear products_trousers products_knitted products_sportswear products_nightwear products_other
products_jackets products_children products_knitted products_sportswear products_nightwear products_undergarments
products_ladiesshirts products_trousers
products_shirts products_ladiesshirts products_dresses products_children products_vest products_other
products_children products_outerwear products_trousers products_knitted products_sportswear products_undergarments products_vest
products_outerwear products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_outerwear products_trousers products_knitted products_other
products_children products_outerwear products_trousers products_knitted products_nightwear products_vest
products_jackets products_children products_outerwear products_sweaters
products_ladiesshirts products_dresses products_children products_outerwear products_vest
products_children products_outerwear products_trousers products_knitted products_undergarments
products_shirts products_ladiesshirts products_children products_knitted products_nightwear
products_ladiesshirts products_outerwear products_knitted products_other
products_children products_outerwear products_trousers products_knitted products_undergarments products_other
products_shirts products_ladiesshirts products_children products_outerwear products_trousers products_knitted products_other
products_shirts products_ladiesshirts products_children products_outerwear products_trousers products_knitted
products_shirts products_ladiesshirts products_jackets products_children products_trousers products_knitted products_sportswear products_nightwear products_other
products_shirts products_ladiesshirts products_jackets products_outerwear products_trousers products_other
products_trousers products_knitted products_undergarments
products_shirts products_ladiesshirts products_coats products_dresses products_trousers products_nightwear
products_children products_outerwear products_sweaters
shirts children trousers knitted other
trousers knitted other
sweaters
knitted
shirts ladiesshirts jackets dresses children trousers
children knitted
shirts ladiesshirts jackets dresses children trousers knitted nightwear other
shirts ladiesshirts jackets children trousers knitted
jackets trousers knitted other
children trousers
trousers other
knitted other
children outerwear sportswear
knitted nightwear other
shirts ladiesshirts children other
shirts ladiesshirts jackets trousers other
ladiesshirts other
jackets dresses children trousers knitted sportswear nightwear undergarments other
jackets trousers other
children knitted sportswear nightwear undergarments
outerwear trousers knitted undergarments
trousers
other
shirts ladiesshirts jackets children trousers sportswear
shirts ladiesshirts jackets dresses children trousers other
children
children outerwear
trousers knitted sportswear
sweaters other
shirts ladiesshirts trousers knitted other
shirts ladiesshirts jackets children outerwear trousers other
jackets children knitted sportswear
knitted sportswear nightwear other
shirts ladiesshirts jackets children trousers
ladiesshirts children knitted
children trousers knitted other
shirts ladiesshirts children
children outerwear trousers knitted other
jackets children trousers knitted other
ladiesshirts children trousers
shirts trousers other
children sweaters
vest other
shirts ladiesshirts dresses other
ladiesshirts knitted nightwear other
ladiesshirts outerwear other
jackets trousers knitted sportswear other
children trousers knitted
ladiesshirts jackets children other
children knitted nightwear
jackets knitted
trousers knitted
shirts ladiesshirts children trousers
outerwear sportswear other
shirts ladiesshirts jackets dresses children trousers knitted sportswear nightwear
shirts ladiesshirts jackets children trousers other
ladiesshirts jackets children outerwear trousers
jackets children trousers
shirts ladiesshirts children knitted
shirts ladiesshirts dresses trousers knitted
shirts jackets dresses knitted
jackets knitted sportswear
shirts ladiesshirts trousers
knitted sportswear
jackets trousers
shirts ladiesshirts other
jackets children trousers nightwear
shirts ladiesshirts dresses children trousers other
shirts trousers knitted
shirts ladiesshirts children outerwear trousers other
shirts jackets children trousers
children other
jackets children trousers knitted sportswear other
trousers knitted nightwear
ladiesshirts jackets coats children outerwear trousers
jackets trousers knitted sportswear
children outerwear trousers knitted
shirts ladiesshirts coats dresses children trousers
shirts jackets children trousers knitted sportswear
shirts children other
outerwear knitted sportswear other
children trousers knitted nightwear undergarments other
shirts ladiesshirts jackets trousers
shirts ladiesshirts
ladiesshirts children trousers knitted
shirts ladiesshirts coats trousers knitted
children outerwear knitted sportswear other
shirts trousers nightwear
shirts
shirts ladiesshirts jackets children trousers knitted sportswear
shirts ladiesshirts jackets knitted other
ladiesshirts jackets children trousers knitted
shirts ladiesshirts dresses children trousers knitted other
shirts ladiesshirts dresses children outerwear trousers other
shirts ladiesshirts children trousers knitted
ladiesshirts jackets children outerwear trousers sweaters
children outerwear other
jackets children trousers knitted
ladiesshirts jackets trousers vest other
children trousers other
shirts ladiesshirts knitted other
shirts ladiesshirts trousers other
outerwear trousers other
shirts ladiesshirts trousers sportswear
ladiesshirts knitted
jackets
shirts jackets trousers knitted other
jackets trousers knitted nightwear undergarments
shirts trousers knitted other
shirts ladiesshirts children trousers other
knitted sportswear undergarments
shirts jackets trousers
undergarments
shirts ladiesshirts jackets knitted nightwear
shirts ladiesshirts jackets children sweaters
jackets coats children outerwear trousers knitted sportswear vest
jackets children knitted nightwear
shirts ladiesshirts dresses children trousers sportswear
shirts ladiesshirts children knitted other
children trousers knitted sportswear
shirts ladiesshirts dresses
coats
outerwear trousers knitted sportswear
children outerwear sportswear other
shirts ladiesshirts jackets outerwear trousers other
sportswear
shirts ladiesshirts jackets children sportswear other
shirts ladiesshirts jackets coats children outerwear trousers knitted sportswear undergarments other
jackets trousers knitted
ladiesshirts children outerwear trousers knitted
shirts jackets children outerwear trousers
shirts ladiesshirts jackets children trousers knitted nightwear
knitted nightwear
shirts jackets coats children outerwear trousers
ladiesshirts jackets children outerwear knitted
ladiesshirts
children outerwear trousers knitted sportswear other
children outerwear sweaters
shirts other
shirts knitted other
shirts children
shirts ladiesshirts children outerwear
jackets outerwear
jackets coats children outerwear trousers knitted sportswear other
knitted undergarments
shirts ladiesshirts jackets knitted nightwear other
trousers knitted nightwear other
shirts ladiesshirts dresses children other
shirts ladiesshirts jackets children trousers knitted other
shirts ladiesshirts children outerwear other
shirts ladiesshirts trousers knitted
ladiesshirts jackets children outerwear
jackets other
shirts dresses children outerwear knitted vest other
shirts jackets children trousers knitted other
shirts ladiesshirts coats children trousers knitted sportswear nightwear undergarments
children knitted sportswear
knitted sportswear nightwear
shirts ladiesshirts jackets outerwear trousers knitted other
shirts ladiesshirts jackets other
outerwear knitted
shirts ladiesshirts jackets
knitted nightwear undergarments
sweaters vest
ladiesshirts jackets coats outerwear trousers
ladiesshirts jackets trousers other
shirts children knitted
jackets outerwear trousers
shirts trousers
jackets children trousers knitted sportswear nightwear undergarments other
children knitted undergarments
ladiesshirts children
jackets children trousers knitted nightwear vest other
children outerwear trousers nightwear undergarments
trousers knitted sportswear nightwear vest other
shirts ladiesshirts dresses children outerwear trousers knitted other
jackets trousers knitted sportswear nightwear
children outerwear knitted other
ladiesshirts jackets children outerwear trousers vest other
trousers knitted undergarments
children knitted other
shirts jackets children knitted other
outerwear trousers knitted other
shirts jackets trousers other
jackets trousers sportswear
ladiesshirts children other
shirts ladiesshirts jackets dresses children outerwear trousers knitted other
shirts ladiesshirts jackets children outerwear trousers sportswear nightwear
shirts ladiesshirts knitted
trousers sportswear
jackets outerwear trousers other
jackets trousers knitted nightwear other
trousers knitted sportswear undergarments other
knitted sportswear other
jackets children knitted
ladiesshirts trousers knitted
shirts ladiesshirts dresses children sportswear
shirts ladiesshirts dresses children trousers
shirts ladiesshirts jackets coats children trousers knitted sweaters
jackets children trousers outerwear
jackets children trousers knitted sportswear
shirts ladiesshirts jackets dresses children trousers knitted
children trousers knitted sportswear nightwear
jackets children outerwear trousers knitted sportswear nightwear
shirts ladiesshirts jackets trousers children knitted
shirts ladiesshirts jackets children trousers nightwear undergarments
jackets dresses children knitted
shirts ladiesshirts coats trousers
jackets trousers outerwear sportswear
dresses children trousers
ladiesshirts children knitted sportswear nightwear
jackets outerwear trousers sportswear sweaters
ladiesshirts children trousers other
children trousers undergarments other
shirts ladiesshirts children trousers sportswear
children trousers knitted nightwear undergarments
jackets children trousers sportswear
ladiesshirts jackets outerwear trousers knitted sportswear nightwear undergarments vest
children trousers sportswear
shirts ladiesshirts jackets dresses children knitted sportswear
children knitted sweaters vest
ladiesshirts coats children outerwear knitted
jackets children trousers knitted sportswear undergarments
jackets outerwear trousers sportswear
jackets children outerwear trousers
ladiesshirts children outerwear trousers knitted sportswear nightwear sweaters vest
jackets outerwear trousers sportswear vest
shirts ladiesshirts children outerwear trousers
knitted children nightwear undergarments jackets ladiesshirts shirts
shirts knitted
shirts ladiesshirts Trousers jackets
sweaters vest other
jackets children knitted sportswear other
jackets dresses trousers knitted sportswear nightwear undergarments other
coats trousers knitted
shirts ladiesshirts jackets trousers knitted sweaters
dresses knitted nightwear
shirts ladiesshirts jackets coats children trousers
children knitted sportswear nightwear
undergarments other
shirts ladiesshirts jackets children knitted
shirts ladiesshirts jackets coats dresses children outerwear trousers knitted sportswear nightwear
jackets coats children trousers
trousers knitted sportswear undergarments
shirts ladiesshirts children trousers knitted sportswear other
outerwear
shirts ladiesshirts jackets trousers knitted other
knitted sweaters other
jackets children trousers knitted sportswear undergarments other
shirts ladiesshirts jackets trousers knitted sweaters other
jackets knitted other
ladiesshirts jackets children outerwear trousers knitted nightwear
ladiesshirts jackets children trousers knitted nightwear vest other
jackets children trousers knitted nightwear undergarments vest other
children knitted sportswear undergarments
shirts ladiesshirts jackets children knitted other
gloves other
jackets knitted sportswear undergarments
jackets children outerwear trousers knitted sportswear nightwear undergarments
knitted sportswear sweaters
shirts ladiesshirts jackets children knitted sportswear
shirts ladiesshirts trousers knitted sweaters
shirts ladiesshirts jackets children knitted sweaters
jackets trousers sportswear nightwear
shirts ladiesshirts jackets trousers knitted sportswear
shirts ladiesshirts jackets dresses children trousers knitted sportswear other
shirts ladiesshirts jackets dresses children trousers knitted nightwear
dresses children trousers knitted sportswear nightwear other
children trousers knitted nightwear
shirts jackets children trousers other
ladiesshirts nightwear
ladiesshirts jackets trousers knitted sportswear nightwear
jackets coats trousers knitted sportswear nightwear undergarments sweaters other
ladiesshirts jackets children trousers knitted other
children outerwear knitted sportswear nightwear
shirts ladiesshirts jackets dresses children outerwear trousers knitted sportswear nightwear undergarments
dresses children outerwear trousers knitted sportswear nightwear
children knitted nightwear undergarments
children trousers sportswear other
jackets children trousers knitted sportswear vest other
shirts ladiesshirts jackets dresses children outerwear trousers sportswear nightwear vest other
shirts ladiesshirts children trousers nightwear other
shirts ladiesshirts jackets children trousers knitted sportswear vest
shirts ladiesshirts jackets children outerwear trousers knitted sportswear
shirts ladiesshirts dresses children trousers sportswear nightwear
ladiesshirts jackets dresses children trousers sportswear nightwear other
gloves
shirts ladiesshirts jackets dresses children outerwear trousers other
dresses children trousers other
shirts ladiesshirts jackets children
trousers knitted sportswear nightwear other
jackets coats other
children trousers knitted sportswear undergarments
jackets outerwear trousers knitted other
outerwear trousers knitted
knitted nightwear undergarments gloves
shirts ladiesshirts children trousers nightwear
shirts jackets coats outerwear trousers
jackets children knitted other
jackets trousers knitted undergarments
shirts ladiesshirts jackets children outerwear trousers knitted sportswear nightwear
jackets children trousers knitted nightwear other
shirts ladiesshirts jackets children trousers knitted sportswear nightwear
jackets children trousers knitted nightwear undergarments
jackets children outerwear trousers knitted undergarments
children knitted sportswear undergarments vest other
jackets children trousers knitted sportswear nightwear
children trousers knitted nightwear other
jackets children trousers knitted undergarments other
ladiesshirts jackets children trousers knitted sportswear other
ladiesshirts jackets children
shirts jackets children knitted sweaters
children trousers sportswear nightwear undergarments
children knitted nightwear other
jackets children trousers knitted sportswear nightwear other
ladiesshirts jackets coats dresses trousers knitted nightwear undergarments vest
shirts ladiesshirts jackets trousers sportswear other
shirts ladiesshirts jackets children trousers knitted nightwear other
ladiesshirts jackets coats dresses children trousers knitted sportswear nightwear undergarments coordinate gloves sweaters vest
jackets children trousers knitted sportswear nightwear undergarments
jackets children knitted nightwear undergarments
shirts ladiesshirts jackets dresses other
shirts ladiesshirts jackets dresses children outerwear trousers knitted nightwear undergarments other
shirts ladiesshirts dresses children undergarments
children trousers knitted sportswear nightwear undergarments other
children trousers nightwear
knitted sportswear nightwear undergarments
dresses children trousers sportswear nightwear
trousers knitted sportswear undergarments sweaters
jackets coats children trousers knitted
coats other
shirts ladiesshirts jackets children outerwear trousers
jackets dresses outerwear trousers
trousers knitted undergarments other
children trousers knitted undergarments other
ladiesshirts jackets dresses trousers knitted sportswear
coats trousers other
shirts ladiesshirts trousers knitted sportswear
jackets dresses knitted other
sportswear other
jackets coats children outerwear trousers other
shirts ladiesshirts children trousers knitted sportswear nightwear other
knitted sportswear nightwear undergarments other
shirts ladiesshirts jackets coats trousers
ladiesshirts jackets coats children trousers
ladiesshirts jackets other
jackets dresses children trousers knitted sportswear other
shirts ladiesshirts jackets knitted
ladiesshirts jackets children trousers
vest
shirts ladiesshirts jackets children other
children outerwear trousers other
coats knitted
shirts jackets children outerwear other
trousers knitted sportswear other
shirts jackets other
shirts jackets children other
shirts ladiesshirts jackets children knitted sportswear nightwear
shirts children trousers
jackets children outerwear trousers knitted sportswear undergarments
children knitted nightwear vest
trousers jackets knitted sportswear other
coats trousers
shirts ladiesshirts jackets trousers knitted sportswear nightwear
ladiesshirts children trousers knitted nightwear undergarments
jackets trousers knitted sportswear nightwear other
shirts ladiesshirts jackets children trousers nightwear
knitted trousers other
shirts ladiesshirts jackets coats dresses children outerwear trousers knitted nightwear undergarments coordinate sweaters vest
knitted trousers
shirts ladiesshirts jackets coats children knitted other
children trousers shirts dresses coats other outerwear
shirts jackets knitted trousers sportswear other
shirts ladiesshirts dresses children trousers knitted sportswear
ladiesshirts jackets
shirts ladiesshirts jackets outerwear trousers
dresses trousers other
coats children trousers knitted sportswear
coats children knitted
jackets coats children knitted undergarments
shirts ladiesshirts jackets coats dresses children outerwear trousers knitted sportswear nightwear undergarments
jackets knitted trousers sportswear other
trousers children other
sportswear nightwear undergarments
shirts ladiesshirts trousers sportswear nightwear other
ladiesshirts children knitted nightwear
shirts dresses children trousers knitted other
shirts ladiesshirts children knitted nightwear other
children jackets trousers knitted sportswear other
shirts ladiesshirts jackets children outerwear trousers knitted sportswear nightwear undergarments
shirts ladiesshirts jackets trousers knitted sportswear dresses coats children nightwear undergarments
jackets other children knitted sportswear
ladiesshirts jackets other dresses children outerwear trousers knitted sportswear vest
jackets other dresses children outerwear trousers sportswear vest
knitted sportswear nightwear sweaters vest other
children outerwear sweaters vest
ladiesshirts jackets children trousers knitted sportswear nightwear other
jackets children outerwear knitted sportswear nightwear undergarments
jackets children outerwear knitted sportswear nightwear
ladiesshirts jackets trousers
children trousers knitted sportswear other
shirts ladiesshirts jackets other dresses children trousers knitted
jackets trousers knitted sportswear nightwear vest other
ladiesshirts jackets children trousers knitted sportswear sweaters vest shirts coats dresses outerwear other
jackets trousers knitted sportswear other children
jackets children knitted sportswear nightwear undergarments
ladiesshirts jackets children trousers knitted sportswear nightwear undergarments
shirts jackets trousers knitted sportswear other
shirts ladiesshirts jackets children trousers vest
knitted jackets trousers other
shirts jackets children trousers knitted
dresses trousers
shirts jackets outerwear trousers sportswear other
jackets children outerwear sweaters other
jackets children trousers knitted undergarments vest other
shirts ladiesshirts trousers sweaters
shirts ladiesshirts jackets dresses children outerwear trousers
shirts ladiesshirts dresses children
coats dresses children outerwear knitted nightwear
jackets children knitted sportswear nightwear other
shirts ladiesshirts jackets children outerwear trousers sportswear
shirts jackets knitted other
trousers other knitted sportswear
trousers children knitted jackets other
jackets children knitted nightwear other
jackets dresses children outerwear trousers knitted sportswear nightwear undergarments other
shirts ladiesshirts jackets children outerwear knitted
shirts ladiesshirts jackets children outerwear
shirts ladiesshirts jackets children trousers vest other
jackets coats dresses children outerwear trousers sportswear nightwear undergarments vest other
children trousers knitted undergarments
trousers knitted nightwear undergarments other
children trousers other knitted
knitted sportswear children
ladiesshirts jackets outerwear knitted
shirts ladiesshirts jackets coats children trousers sportswear undergarments
jackets shirts ladiesshirts coats children undergarments
jackets children outerwear knitted undergarments
shirts ladiesshirts children trousers sportswear other
jackets children trousers other
knitted sportswear trousers children
shirts trousers knitted sweaters other
jackets coats children trousers knitted sportswear nightwear undergarments vest
ladiesshirts jackets dresses children
ladiesshirts jackets dresses children knitted
children knitted nightwear jackets
jackets shirts trousers other
jackets coats children knitted nightwear
jackets dresses children trousers sportswear
jackets children trousers sportswear other
knitted jackets ladiesshirts children
jackets knitted sportswear other trousers
dresses children trousers sportswear
knitted trousers children
knitted sportswear undergarments other
shirts ladiesshirts jackets other trousers sportswear
trousers jackets
jackets dresses children trousers knitted undergarments
jackets dresses children trousers knitted sportswear nightwear undergarments
ladiesshirts shirts children trousers other
shirts ladiesshirts nightwear
ladiesshirts jackets trousers knitted
ladiesshirts jackets dresses
jackets dresses children outerwear trousers other
trousers sportswear knitted other
ladiesshirts jackets children outerwear trousers knitted
    '''

# %%

process_lines = processes_raw.split("\n")
processes = list()
for process in process_lines:
    if "|" in process:
        processes = processes + [p.strip() for p in process.split("|") if p]
    elif " " in process:
        processes = processes + [p.strip() for p in process.split(" ") if p]
    else:
        processes = processes + [p.strip() for p in process.split() if p]

processes
# %%
processes = list(set(processes))

process_map = {
    'factory_processsewing': "Sewing",
    'factory_processfinishing': "Finishing and Packing",
    'factory_processtrimming': "Trimming and Mending",
    'factory_processprinting': "Printing",
    'dyeing': "Dyeing",
    'factory_processembroidery': "Embroidery",
    'other': "Other",
    'strimming': "Trimming and Mending",
    'trimming': "Trimming and Mending",
    'finishing': "Finishing and Packing",
    'cutting': "Cutting",
    'factory_processother': "Other",
    'factory_processwashing': "Washing",
    'swinding': "Winding",
    'factory_processweaving': "Weaving",
    'knitting': "Knitting",
    'washing': "Washing",
    'factory_processknitting': "Knitting",
    'factory_processdyeing': "Dyeing",
    'embroidery': "Embroidery",
    'winding': "Winding",
    'factory_processwinding': "Winding",
    'factory_processcutting': "Cutting",
    'linking': "Linking",
    'weaving': "Weaving",
    'printing': "Printing",
    'sewing': "Sewing"
}
# %%

translated_processes = list()
for process in process_lines:
    if "|" in process:
        t_process = [process_map[p.strip()] for p in process.split("|") if p]
        t_process.sort()
        t_process = ", ".join(t_process)
        translated_processes.append(t_process)
    elif " " in process:
        t_process = [process_map[p.strip()] for p in process.split(" ") if p]
        t_process.sort()
        t_process = ", ".join(t_process)
        translated_processes.append(t_process)
    else:
        print("not found " + process)


# %%
translated_processes = list(set(translated_processes))
translated_processes.sort()
with open('./outputs/process_list.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    for p in translated_processes:
        writer.writerow([p])


# %%
factory_types = {
    'factory_typeknit': "Knit Garment",
    'factory_typewoven': "Woven Garment",
    'factory_typeother': "Other",
    'factory_typecomposite': "Knit Composite",
    'factory_typesweater': "Sweater",
    'woven': "Woven Garment",
    'knit': "Knit Garment",
    'sweater': "Sweater",
    'other': "Other",
    'knitcomposite': "Knit Composite",
    'Woven': "Woven Garment",
    'Knit': "Knit Garment",
    'Sweater': "Sweater",
    'Washing': "Washing",
    "Knit Composite": "Knit Composite",
    "Fabric Knitting": "Fabric Knitting",
    'Dyeing': "Dyeing",
    'Knitting': "Knit Garment",
    'Cap': "Cap",
    'Finishing': "Finishing",
    'Composite': "Knit Composite",
    'Accessories': "Accessories",
    'Footwear': "Footwear",
    'Printing': "Printing",
    "Textile Mills": "Textile Mills",
    "Shoe Factory": "Shoe Factory",
    "Spinning Mills": "Spinning Mills",
    "Home tex": "Home tex",
    "Socks": "Socks"
}

with open('./outputs/type_list.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    factory_types = {k: v for k, v in sorted(
        factory_types.items(), key=lambda item: item[1])}
    for p in factory_types:
        writer.writerow([p, factory_types[p]])


# %%
